author: Ahmad Mahmoodian Darishani
summary: Ahmad's Personal Page
lang: en
locale: en_US
url: "https://ahmadrv.github.io/"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  posts_limit: 20
